{-
   Hello World App
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   The version of the OpenAPI document: 0.0.1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.HelloWorldResponse exposing (HelloWorldResponse, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias HelloWorldResponse =
    { message : String
    }


decoder : Decoder HelloWorldResponse
decoder =
    Decode.succeed HelloWorldResponse
        |> required "message" Decode.string


encode : HelloWorldResponse -> Encode.Value
encode model =
    Encode.object
        [ ( "message", Encode.string model.message )
        ]
