{-
   Hello World App
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   The version of the OpenAPI document: 0.0.1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.Insurance exposing (Insurance, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias Insurance =
    { insuranceType : String
    , provider : String
    }


decoder : Decoder Insurance
decoder =
    Decode.succeed Insurance
        |> required "insuranceType" Decode.string
        |> required "provider" Decode.string


encode : Insurance -> Encode.Value
encode model =
    Encode.object
        [ ( "insuranceType", Encode.string model.insuranceType )
        , ( "provider", Encode.string model.provider )
        ]
